### ISSUE TITLE
Generate a Debian package

### ISSUE THREAD

**Issue by AlexandreBonneau** [t3rm1n4l/go-mega#27]
Hi, rclone mega backend cannot be activated under Debian since it depends on go-mega, which is not packaged (see this [issue](https://github.com/rclone/rclone/issues/3980)).

Would it be possible to package go-mega as a Debian package?

**Comment by ncw** [comment]
It would be necessary to find a Debian maintainer to package it. Although I do maintain the go-mega package, I'm not a debian maintainer.

**Comment by blademckain** [comment]
please create a package for debian

**Comment by web-pat** [comment]
How much effort would that be to create a debian package and maintain it, specifically in this case? I'd volunteer to do so but have had no previous experience maintaining a package.

**Comment by AlexandreBonneau** [comment]
@web-pat well, you can try :)

**Comment by ncw** [comment]
This needs a debian maintainer to add go-mega to debian as a debian source package.

This isn't something we (the maintainers of go-mega) can do, it needs to be a debian maintainer.

You can try filing a Debian Request For Package if you can work out how!

**Comment by maltfield** [comment]
@toddy15 or @dmferrari or @bertogg

would any of you be willing to help package this for debian? This blocks mega support in rclone

 * https://github.com/rclone/rclone/issues/3980

**Comment by firrsefu** [comment]
I've created a "bug" under Work-Needing and Prospective Packages to request go-mega be added to Debian so rclone can work with Mega.nz storage: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1039997

**Comment by Maytha8** [comment]
Letting you know that I've packaged this in Debian (it's just been accepted into Debian Unstable).

https://tracker.debian.org/pkg/golang-github-t3rm1n4l-go-mega

**Comment by ncw** [comment]
I'll close this now then - thank you @Maytha8 :-)
