### ISSUE TITLE
How to fetch filesystem tree

### ISSUE THREAD

**Issue by Numenorean** [t3rm1n4l/go-mega#28]
I don't understand how to do it. There is no method to do this

**Comment by ncw** [comment]
First call `Login` then get look in the `Mega` object returned for the `FS` parameter. That is a MegaFS node which has these methods

You can find individual nodes or traverse the file system with these methods.

```
func (fs *MegaFS) GetChildren(n *Node) ([]*Node, error)
func (fs *MegaFS) GetInbox() *Node
func (fs *MegaFS) GetRoot() *Node
func (fs *MegaFS) GetSharedRoots() []*Node
func (fs *MegaFS) GetTrash() *Node
func (fs *MegaFS) HashLookup(h string) *Node
func (fs *MegaFS) PathLookup(root *Node, ns []string) ([]*Node, error)
```

See: https://pkg.go.dev/github.com/t3rm1n4l/go-mega for more docs

**Comment by Numenorean** [comment]
> First call `Login` then get look in the `Mega` object returned for the `FS` parameter. That is a MegaFS node which has these methods
> 
> You can find individual nodes or traverse the file system with these methods.
> 
> ```
> func (fs *MegaFS) GetChildren(n *Node) ([]*Node, error)
> func (fs *MegaFS) GetInbox() *Node
> func (fs *MegaFS) GetRoot() *Node
> func (fs *MegaFS) GetSharedRoots() []*Node
> func (fs *MegaFS) GetTrash() *Node
> func (fs *MegaFS) HashLookup(h string) *Node
> func (fs *MegaFS) PathLookup(root *Node, ns []string) ([]*Node, error)
> ```
> 
> See: https://pkg.go.dev/github.com/t3rm1n4l/go-mega for more docs

Is it possible to do output like in Linux command "tree"?

**Comment by ncw** [comment]
If you want that kind of thing, I suggest you install rclone (https://rclone.org) and use the [mega backend](https://rclone.org/mega/). You can then use `rclone tree mega:`. Rclone uses the go-mega library.

**Comment by Numenorean** [comment]
finally i made this with the example in this video: https://www.youtube.com/watch?v=XbKSssBftLM
