### ISSUE TITLE
Can't retrieve size of folder

### ISSUE THREAD

**Issue by Numenorean** [t3rm1n4l/go-mega#29]
Is it a bug? is always returns 0

**Comment by ncw** [comment]
Do you mean when calling `Size()` on a `Node`? I think 0 is what you get - it doesn't count stuff inside the Node.

**Comment by Numenorean** [comment]
> Do you mean when calling `Size()` on a `Node`? I think 0 is what you get - it doesn't count stuff inside the Node.
exactly, is that has only one solution? like using recursion

**Comment by Numenorean** [comment]
> > Do you mean when calling `Size()` on a `Node`? I think 0 is what you get - it doesn't count stuff inside the Node.
exactly, is that has only one solution? like using recursion

**Comment by ncw** [comment]
I think recursion is the only answer - I don't think the API provides it. In general it is quite expensive to compute and keep up to date so most cloud storage providers don't provide this info.
