### ISSUE TITLE
Add use https option

### ISSUE THREAD

**Issue by NodudeWasTaken** [t3rm1n4l/go-mega#42]
Some ISPs like to throttle http
To address this, i can use "use https only" in megacmd, which grants me decent download speeds compared to the poor ones of http only.
Is there any chance you might implement this?

Relevant links:
https://github.com/meganz/MEGAcmd/blob/master/UserGuide.md#https
https://github.com/meganz/sdk/blob/6175b23c702fce7908b9b9adbf922456f48ca86e/examples/megacli.cpp#L7876
https://github.com/meganz/sdk/blob/6175b23c702fce7908b9b9adbf922456f48ca86e/examples/megacli.cpp#L2597
https://github.com/meganz/sdk/blob/6175b23c702fce7908b9b9adbf922456f48ca86e/src/commands.cpp#L53

**Comment by ncw** [comment]
Can you make a pull request for this?

**Comment by NodudeWasTaken** [comment]
> Can you make a pull request for this?

While i did try, i cannot tell if my changes actually work as intended, except for the tests passing with usehttps on.
