### ISSUE TITLE
Fails to build on ARM Ubuntu

### ISSUE THREAD

**Issue by baskervald** [t3rm1n4l/go-mega#8]
Fails to build with this error on ARM Ubuntu, running within a Chrome OS chroot using [dnschneid/crouton](https://github.com/dnschneid/crouton), although given my use of it so far, I find it very reasonable to assume that this would be the case even if I weren't running it the way I am.

```
(precise)ashlynn@localhost:~/build/go-mega$ make
go build
# _/home/ashlynn/build/go-mega
./utils.go:54: buf.Grow undefined (type *bytes.Buffer has no field or method Grow)
make: *** [build] Error 2
```

**Comment by x62275** [comment]
i have this too

**Comment by 8L4D3** [comment]
Me too, on a x64 Debian Wheezy server.

**Comment by sogko** [comment]
Hi guys,

I'm curious, whats the version of Go are you guys using? Because if I understand it correctly, `buf.Grow()` is from the standard Go `bytes` package (version 1.4.2 for me)

```bash
$ go version
```

**Comment by ncw** [comment]
This problem is caused by using an old version of go.  The travis tests now test building on go 1.6-go1.9 so I don't think this is a problem any more if you use a recent version of go.
